name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Runs a set of commands using the runners shell
      - name: Build and test
        run: |
          sudo apt-get update 
          sudo apt-get install -y apt-utils \
          build-essential \
          cmake \
          googletest \
          libtbb-dev \
          libboost-all-dev \
          liblapack-dev \
          wget
          wget https://github.com/simbody/simbody/archive/Simbody-3.7.tar.gz
          tar xvzf Simbody-3.7.tar.gz
          rm Simbody-3.7.tar.gz
          mkdir ./simbody-build
          mkdir /home/runner/simbody
          export simbody_install_path=$(pwd)/simdody
          cd ./simbody-build
          cmake ../simbody-Simbody-3.7 -DCMAKE_INSTALL_PREFIX=/home/runner/simbody -DCMAKE_BUILD_TYPE=RelWithDebInfo -DBUILD_VISUALIZER=off -DBUILD_STATIC_LIBRARIES=on
          make -j$(nproc)
          # && ctest -j$(nproc)
          make -j$(nproc) install
          cd ..
          export TBB_HOME=/usr/lib/x86_64-linux-gnu
          export BOOST_HOME=/usr/lib/x86_64-linux-gnu
          export SIMBODY_HOME=/home/runner/simbody
          mkdir build
          cd build 
          cmake ..
          make -j$(nproc)
          ctest --output-on-failure
